Feature/update of dashbooards templates
Sciance-Inc/core.dashboards_store pull request #52
Opened 2024-04-30 00:48 UTC by EricMarcotte

# Objectives of the Pull Request ? 
>Mise à jour des gabarits des tableaux de bord pour ajouter des variables de déploiement. Uniformisation du stamper et des visuels. 

# What is left out of the Pull Request ? 
> Le tableau abstenteeism est exclue de la PR car il est en cours de dévelopement.
Du travail sur les visuels de emp_conge restent à effectuer lors de sa prochaine révision.

# How to run the pull request ?
Simplement déployer les PBIT en ajoutant les variables à l'ouverture des tableaux

```

# Checklist
> Please, read carefully each item before checking it. Your PR's review might be delayed otherwise.

* **Code** :
  * [X] The code I'm asking a review for is working. **I understand that my PR will be rejected as-is otherwise.**
  * [X] My code follows the conventions described in the `contribution guide`.
  * [X] My `models` / `seeds` / `adapters` are tested and documented in DBT 9through the `yaml` files.
  * I have a added a new **mandatory seed** / a new **mandatory adapter** : 
    * [ ] I have you populated the `tooling/nightly` project with my new seed / adapter.
    * [ ] An exemple of how to populate the adapter can be found in the `analysis` folder.
  * I have added a new **dashboard** : 
    * [ ] I have updated the `core.dashboards_store/tooling/template/{{ cookiecutter.css_short_name + '.dashboards_store' }}/dbt_project.yml` file with my new dashboard. 
    * [ ] I have added a new `doc` page in the `core.dashboards_store/tooling/docs/content/` appropriate folder, describing what my dashboards does and how to configure it.
    * [X] The dashboard is saved with `.pbit` extension, **not** a `.pbix` extension, so it doesn't contains any data.
  * [ ] I have called `sqfmt .` to format my code, and **made sure my code was still running as expected after having been reformated**.
* **Documentation** : 
  * [X]  I have updated the documentation (README) accordingly to my changes.
  * [ ]  The models I have added are documented in a `schema.yml` file.
* **Pull-request** : 
  * [X]  My merge message is prefixed with a `commitizen` key word so it looks something like `<feat|fix|chore|doc|refactor|perf|style>: foo bar`**
  * [X]  The code *provided to run the pull request* is working. **I understand that my PR will be rejected as-is otherwise.**
  * [X]  My pull request is documented. I have explained the needs for the PR, what was left out of the it and why.
  * [X]  I have carefully reviewd each changes made to a file and made sure the files included on the PR were actually added on purpose.
  * [X]  I have assignee at least **1** people to review my PR.

2024-05-01 00:26 UTC, hugoJuhel requested changes
@EricMarcotte 

enjeux au niveau du stamper ; a verifier c'est a cause du passage en template mais je ne pense pas car il marche à certaines fois.

Quelques soucis  mineurs de mise en forme / pages.

optionnellement, a checker, configurer le filtre du stamper en utilisant la data de _sufffixe_dashboard pour eviter les enjeux

2024-05-01 00:26 UTC, hugoJuhel commented on reporting/educ_serv/res_epreuves/rslt_epreuves.pbit
@EricMarcotte 
![image](https://github.com/Sciance-Inc/core.dashboards_store/assets/22279443/d078b815-b576-4c59-8b4a-0b1fffb00dd4)


Filtres du stamper

2024-05-01 00:26 UTC, hugoJuhel commented on reporting/educ_serv/suivi_resultats/suivi_resultats.pbit
@EricMarcotte 

Filtres stamper

2024-05-01 00:26 UTC, hugoJuhel commented on reporting/educ_serv/res_scolaires/res_scolaires.pbit
@EricMarcotte 

Filtres stamper

2024-05-01 00:26 UTC, hugoJuhel commented on reporting/human_resources/retirement/retirement.pbit
@EricMarcotte 

![image](https://github.com/Sciance-Inc/core.dashboards_store/assets/22279443/7e8d351d-0a83-4e74-9e03-5fd1416a3eac)


Le styamper ne devrait apparaitre qu'une seule fois,.

un de deux filtre est bon

2024-05-01 00:26 UTC, hugoJuhel commented on reporting/human_resources/emp_actif/emp_actif.pbit
@EricMarcotte 

filtres stamper

![image](https://github.com/Sciance-Inc/core.dashboards_store/assets/22279443/2f930e9c-3d7a-4264-b433-461959a8541d)

2024-05-01 00:26 UTC, hugoJuhel commented on reporting/human_resources/emp_conge/emp_conge.pbit
@EricMarcotte 
![image](https://github.com/Sciance-Inc/core.dashboards_store/assets/22279443/08eee7f8-930f-4926-98b6-dff42a1673c5)

Filtres stamper

Cartouche de description dud ahsboard.

2024-05-01 01:05 UTC, EricMarcotte commented on reporting/gabarit_tdb/gabarit.pbit
Solved de la facon suivante : 
![image](https://github.com/Sciance-Inc/core.dashboards_store/assets/71104800/2aa67115-4c4f-49f9-977d-61344bd5d411)

2024-05-01 01:08 UTC, EricMarcotte commented on reporting/gabarit_tdb/gabarit.pbit
Fixed !

2024-05-01 01:15 UTC, EricMarcotte commented on reporting/gabarit_tdb/gabarit.pbit
Fixed and bonified 
![image](https://github.com/Sciance-Inc/core.dashboards_store/assets/71104800/431f3d47-2205-447b-ae4b-91cb87474038)

2024-05-01 03:33 UTC, EricMarcotte commented on reporting/gabarit_tdb/gabarit.pbit
On ne peut retourner null car ca souleve un autre enjeux mais voici la solution : 
![image](https://github.com/Sciance-Inc/core.dashboards_store/assets/71104800/a372ffbc-2db3-4d5a-b444-58b616380ac1)

2024-05-01 04:08 UTC, EricMarcotte commented on reporting/educ_serv/res_epreuves/rslt_epreuves.pbit
Fixed de la même facon que dans le gabarit!

2024-05-01 04:11 UTC, EricMarcotte commented on reporting/educ_serv/res_epreuves/rslt_epreuves.pbit
Mon erreur ! Fixed !

2024-05-01 04:26 UTC, EricMarcotte commented on reporting/educ_serv/chronic_absenteeism/chronic_absenteism.pbit
J'en ai profiter pour ajouter la nouvelle version de l'anomisateur et le suffixe

2024-05-01 04:34 UTC, EricMarcotte commented on reporting/educ_serv/effectif_css/effectif_css.pbit
Corrigé

2024-05-01 04:34 UTC, EricMarcotte commented on reporting/educ_serv/effectif_css/effectif_css.pbit
Corrigé

2024-05-01 04:40 UTC, EricMarcotte commented on reporting/educ_serv/predictive_view_aggregated/predictive_view_aggregated.pbit
@hugoJuhel c'est mon erreur en recopiant le stamper j'ai oublié de modifier cela :-). Fixed !

2024-05-01 04:47 UTC, EricMarcotte commented on reporting/educ_serv/predictive_view_aggregated/predictive_view_aggregated.pbit
Added suffixe and new anonimisator fucntion

2024-05-01 05:03 UTC, EricMarcotte commented on reporting/human_resources/retirement/retirement.pbit
Fixed and updated ano + suffixe

2024-05-01 05:21 UTC, EricMarcotte commented on reporting/human_resources/emp_actif/emp_actif.pbit
Fixed !

2024-05-01 05:24 UTC, EricMarcotte commented on reporting/educ_serv/suivi_resultats/suivi_resultats.pbit
Fixed

2024-05-01 05:37 UTC, EricMarcotte commented on reporting/human_resources/emp_conge/emp_conge.pbit
@hugoJuhel Ok c'est modifié !

2024-05-03 13:38 UTC, hugoJuhel requested changes
@EricMarcotte 

Quelques soucis de stamper.

2024-05-03 13:38 UTC, hugoJuhel commented on reporting/educ_serv/effectif_css/effectif_css.pbit
@EricMarcotte 

![image](https://github.com/Sciance-Inc/core.dashboards_store/assets/22279443/f78c4010-a059-4889-8666-567f7f600463)

Il y a un enjeux sur le stamper de ce tableau de bord. Le filtre du stamper doit etre sur les deux pages dans effectif CSS

2024-05-03 13:38 UTC, hugoJuhel commented on reporting/educ_serv/res_epreuves/rslt_epreuves.pbit
![image](https://github.com/Sciance-Inc/core.dashboards_store/assets/22279443/afcc0565-e529-4f31-840d-75c99492e119)

@EricMarcotte  page ecole.

Probleme sur le filtre du stamper

2024-05-03 13:38 UTC, hugoJuhel commented on reporting/human_resources/retirement/retirement.pbit
@EricMarcotte 

![image](https://github.com/Sciance-Inc/core.dashboards_store/assets/22279443/67de27de-5ac7-4b71-ac2a-72899b4ff096)


Filtres

2024-05-03 18:13 UTC, EricMarcotte commented on reporting/educ_serv/effectif_css/effectif_css.pbit
Solved !

2024-05-03 18:25 UTC, EricMarcotte commented on reporting/educ_serv/res_epreuves/rslt_epreuves.pbit
@hugoJuhel Je me suis assurer que les 3 filtres sont sur résualts épreuves !

2024-05-03 18:31 UTC, EricMarcotte commented on reporting/human_resources/retirement/retirement.pbit
![image](https://github.com/Sciance-Inc/core.dashboards_store/assets/71104800/d2a36e5d-38a6-479c-9d04-bbce8c71e2d1)

2024-05-03 18:32 UTC, EricMarcotte commented on reporting/human_resources/retirement/retirement.pbit
Moi c bon ! 
![image](https://github.com/Sciance-Inc/core.dashboards_store/assets/71104800/4f152ed1-218d-491e-983e-6b31c86b8eab)

2024-05-04 00:10 UTC, hugoJuhel submitted a review, later dismissed
LGTM.

2024-05-04 00:33 UTC, hugoJuhel approved these changes
@EricMarcotte 

LGTM.

Merge dans branche dans develop avec "rebase".

je serais d'avis de ne pas squasher ! (pas besoin tes commits sont cleans).
mais tu peux le faire si tu trouve qu'un seul commit qui fait tout est plus clean a la lecture

2024-05-04 13:34 UTC, merged