feat: ajouté les tables de rls enseignants et tuteurs
Sciance-Inc/core.dashboards_store pull request #69
Opened 2024-12-10 20:19 UTC by sadqim

# Objectives of the Pull Request ? 
> Describe the high level purpose of your pull request. What are you trying to achieve ? How are you doing it ?
Ajouté les tables qui permette de configurer le RLS dans les différents TDB PowerBI. 
# What is left out of the Pull Request ? 
> Describe what is not included in the pull request. Why did you not include it in the PR. What are the next steps ?
les tables ne sont pas inclus dans les pbit. il reste à les importer dans le pbit et activer le RLS.
# How to run the pull request ?
> Provide the code required to run the pull request. This is the code that will be used to review your pull request. **The provided code must work as-is. If a DBT error is raised while running the code, the PR will be rejected. The following code / placeholder is only provided as documentation / helper to get you started and you will need to adjust it.**

```bash
# Assuming you are in a folder containing both the core.data.store and the <cssXX>.data.store folder.
# Update the code
cd core.dashboards_store
git checkout feature/rls_enseignants
git pull
# Might be required if you update either the poetry file or the lock file
# poetry shell && poetry lock && poetry install 
cd ../cssvdc.dashboards_store
git checkout feature/develop
git pull  
# Might be required if you add a new DBT dependency
# dbt deps
# Run dbt 
dbt build --select +tag:rls+
```

# Checklist
> Please, read carefully each item before checking it. Your PR's review might be delayed otherwise.

* **Code** :
  * [x] The code I'm asking a review for is working. **I understand that my PR will be rejected as-is otherwise.**
  * [x] My code follows the conventions described in the `contribution guide`.
  * [ ] My `models` / `seeds` / `adapters` are tested and documented in DBT 9through the `yaml` files.
  * I have a added a new **mandatory seed** / a new **mandatory adapter** : 
    * [ ] I have you populated the `tooling/nightly` project with my new seed / adapter.
    * [ ] An exemple of how to populate the adapter can be found in the `analysis` folder.
  * I have added a new **dashboard** : 
    * [ ] I have updated the `core.dashboards_store/tooling/template/{{ cookiecutter.css_short_name + '.dashboards_store' }}/dbt_project.yml` file with my new dashboard. 
    * [ ] I have added a new `doc` page in the `core.dashboards_store/tooling/docs/content/` appropriate folder, describing what my dashboards does and how to configure it.
    * [ ] The dashboard is saved with `.pbit` extension, **not** a `.pbix` extension, so it doesn't contains any data.
  * [x] I have called `sqfmt .` to format my code, and **made sure my code was still running as expected after having been reformated**.
* **Documentation** : 
  * [ ]  I have updated the documentation (README) accordingly to my changes.
  * [x]  The models I have added are documented in a `schema.yml` file.
* **Pull-request** : 
  * [x]  My merge message is prefixed with a `commitizen` key word so it looks something like `<feat|fix|chore|doc|refactor|perf|style>: foo bar`**
  * [x]  The code *provided to run the pull request* is working. **I understand that my PR will be rejected as-is otherwise.**
  * [x]  My pull request is documented. I have explained the needs for the PR, what was left out of the it and why.
  * [x]  I have carefully reviewd each changes made to a file and made sure the files included on the PR were actually added on purpose.
  * [x]  I have assignee at least **1** people to review my PR.

2024-12-13 11:47 UTC, hugoJuhel requested changes
Salut @sadqim 

Merci pour la pr ! 

Quelques commentaires mineurs sur les conventions.
Une petite question sur le raionnel derriere le fait d'utiliser deux tables de RLS (une par ordre ens)
Un doute sur les 3 tables de listing donc je ne saisit pas trop l'utilité

2024-12-13 11:47 UTC, hugoJuhel commented on models/rls/enseignants_primaire_tuteurs.sql
> +            and intv.interv = grp.interv_1
@sadqim t'es deux CTE sont les memes modulo la jointure non ?

Pourquoi ne pas L'explrimer dans la jointure

```sql
left join
            {{ ref("i_gpm_t_interv") }} as intv
            on intv.id_eco = grp.id_eco
            and (
                    intv.interv = grp.interv_1 or
                    intv.interv = grp.interv_2
             ) 
```

2024-12-13 11:47 UTC, hugoJuhel commented on models/interfaces/gpi/i_CoursGroupesEleves.sql
@sadqim j<ai un petit doute sur le naming. Penses tu que ton fichier pourra[it etre recommÉ en snake_case comme les autres ?

2024-12-13 11:47 UTC, hugoJuhel commented on models/interfaces/gpi/i_CoursGroupesEleves.sql
@sadqim j<ai un petit doute sur le naming. Penses tu que ton fichier pourra[it etre recommÉ en snake_case comme les autres ?

2024-12-13 11:47 UTC, hugoJuhel commented on models/interfaces/gpi/i_CoursGroupesEnseignants.sql
@sadqim pareil pour le naming des variables, elles sont normallement toutes en snake_case (pour eviter le mix and match)

2024-12-13 11:47 UTC, hugoJuhel commented on models/interfaces/gpi/i_CoursGroupesEleves.sql
@sadqim pareil pour le naming des variables, elles sont normallement toutes en snake_case (pour eviter le mix and match)

2024-12-13 11:47 UTC, hugoJuhel commented on models/rls/enseignants_secondaire.sql
@sadqim je suis curieux, pourquoi séparer les enseignants du secondaire du primaire / tuteur.
Le rationnel reste le meme dUn point de vue RLS non ? Un mapping courriel -> id_du_groupe. Meme si la semantique de l'id de groupe n'est pa necessairement la meme

2024-12-13 11:47 UTC, hugoJuhel commented on models/rls/liste_unique_eleve.sql
@sadqim Je suis curieux, a quoi servent ces tables de liste ? Elles ne sont pas document/es dans le schema donc je ne sais pas si elles sont pertinentes pour le RLS

2024-12-13 11:48 UTC, hugoJuhel commented
@sadqim si tu as besoin de tables intermédiaires aussi, tu as le droit de te faire des sous dossiers pour du staging ou autree.

2024-12-16 15:38 UTC, sadqim commented
> Salut @sadqim
> 
> Merci pour la pr !
> 
> Quelques commentaires mineurs sur les conventions. Une petite question sur le raionnel derriere le fait d'utiliser deux tables de RLS (une par ordre ens) Un doute sur les 3 tables de listing donc je ne saisit pas trop l'utilité

Salut @hugoJuhel, merci pour tes commentaires. je te réponds dans les questions plus bas :)

2024-12-16 15:45 UTC, sadqim commented on models/rls/enseignants_primaire_tuteurs.sql
> +            and intv.interv = grp.interv_1
oui tu as tout à fait raison

2024-12-16 15:46 UTC, sadqim commented on models/interfaces/gpi/i_CoursGroupesEleves.sql
oui

2024-12-16 15:52 UTC, sadqim commented on models/rls/enseignants_secondaire.sql
oui le rationnel est le même sauf que le groupe qui lie l'enseignant à ces élèves est différent entre les enseignants du primaire et les tuteurs au secondaire (groupe repère) et les enseignants du secondaire (cours groupe)

2024-12-17 15:56 UTC, EricMarcotte commented on models/rls/enseignants_primaire_tuteurs.sql
> +            intv.adr_electr is not null
Est-ce possible que parfois l'adresse soit juste un string vide ?

2024-12-17 16:37 UTC, EricMarcotte commented on models/rls/schema.yml
> +            - CompteAuthentification
Snake case  vs all minuscule

2025-01-21 14:26 UTC, hugoJuhel commented
@sadqim je fais la PR demain matin ! (22 janvier)

2025-02-10 15:45 UTC, hugoJuhel commented on models/interfaces/gpi/i_coursgroupeseleves.sql
> +select etablissement as eco, annee, fiche, coursgroupe, matieresgroupes
@sadqim snake_case

2025-02-10 15:45 UTC, hugoJuhel commented on models/interfaces/gpi/i_coursgroupesenseignants.sql
> +select etablissement as ecole, annee, matr_paie, coursgroupe, matieresgroupes
@sadqim snake_case

2025-02-10 15:47 UTC, hugoJuhel commented on models/rls/liste_unique_eleve.sql
@sadqim a mettre dans un dossier bridge

2025-02-10 15:47 UTC, hugoJuhel commented on models/rls/liste_unique_groupes_secondaire.sql
@sadqim a mettre dans un dossier bridge (sous RLS)

2025-02-10 15:47 UTC, hugoJuhel commented on models/rls/enseignants_secondaire.sql
> +select ens.ecole as code_ecole, ens.coursgroupe, id.compteauthentification
@sadqim  snake_case

2025-02-11 19:53 UTC, hugoJuhel approved these changes
noice ! @sadqim

2025-02-11 19:55 UTC, merged